### ISSUE TITLE
Broken Link - Hobbyist Guide

### ISSUE THREAD

**Issue by its-a-lisa** [notpike/SDR-Notes#2]
The link does not not work for The Hobbyist’s Guide to the RTL-SDR → http://libgen.io/book/index.phpDishyTheLovableDish.jpg?md5=858D770EC0E814371C2E0388484CEA5A

**Comment by notpike** [comment]
Looks like http://www.libgen.io/ is down. I found a libgen miror at http://libgen.lc/item/index.php?md5=858D770EC0E814371C2E0388484CEA5A.

Also thanks for finding it! :D
